sudo: false

language: "scala"

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk11

script:
  - sbt clean +test

after_success:
  - ./project/coveralls-settings.sh
  - sbt clean test coverageReport coveralls
